apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mutandae

resources:
  - deployment.yaml
  - deployment-preview.yaml
  - service.yaml
  - service-preview.yaml

images:
  - name: mutandae
    newName: ghcr.io/macel94/mutandae
    newTag: sha-d70ba0af4367242391da27757273ef209a20b564
    digest: sha256:03fa5e01572b66dd1910c5ce411241212908508c5d724733dff24304d6368476
