apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mutandae

resources:
  - deployment.yaml
  - deployment-preview.yaml
  - service.yaml
  - service-preview.yaml

images:
  - name: mutandae
    newName: ghcr.io/macel94/mutandae
    newTag: sha-97dbde1451453cf7252a554e22d4f09b206cfa7c
    digest: sha256:70a84c1f8d4b4f4322a4adc27c413415ecd7c69473f374d59457090ae67ceec8
