apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mutandae

resources:
  - deployment.yaml
  - deployment-preview.yaml
  - service.yaml
  - service-preview.yaml

images:
  - name: mutandae
    newName: ghcr.io/macel94/mutandae
    newTag: sha-960235001554af1d86a39a24d804107c75cd107a
    digest: sha256:f04c954f6f3f32fb13e78c98ce800df8c6864c2245d2fcca7a5237f03420755b
