apiVersion: v1
kind: Service
metadata:
  name: mutandae-preview
  labels:
    app.kubernetes.io/name: mutandae-preview
    belacca.com/project: mutandae
    belacca.com/stage: preview
spec:
  selector:
    app.kubernetes.io/name: mutandae-preview
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
